1.0.1beta2 release prep
open-telemetry/opentelemetry-php-instrumentation pull request #128
Opened 2024-01-27 21:44 UTC by brettmc

2024-01-28 11:52 UTC, agoallikmaa requested changes

2024-01-28 11:52 UTC, agoallikmaa commented on ext/package.xml
> +    <release>1.0.0beta2</release>
```suggestion
    <release>1.0.1beta2</release>
```

2024-01-28 11:52 UTC, agoallikmaa commented on ext/package.xml
> +  <notes>opentelemetry 1.0.0beta2
```suggestion
  <notes>opentelemetry 1.0.1beta2
```

2024-01-29 22:27 UTC, bobstrecansky approved these changes

2024-01-29 22:39 UTC, merged